"""create core tables

Revision ID: 42400cbcfc44
Revises: 347d71577587
Create Date: 2026-09-19 20:39:35.182623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42400cbcfc44'
down_revision: Union[str, Sequence[str], None] = '347d71577587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indices',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indices_code'), 'indices', ['code'], unique=True)
    op.create_index(op.f('ix_indices_is_active'), 'indices', ['is_active'], unique=False)
    op.create_table('sectors',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['sectors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_code'), 'sectors', ['code'], unique=True)
    op.create_index(op.f('ix_sectors_parent_id'), 'sectors', ['parent_id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('subsector', sa.String(length=255), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_companies_sector_id'), 'companies', ['sector_id'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('index_constituents',
    sa.Column('index_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_id', 'company_id', 'effective_from', name='uq_index_constituents_index_company_from')
    )
    op.create_index(op.f('ix_index_constituents_company_id'), 'index_constituents', ['company_id'], unique=False)
    op.create_index(op.f('ix_index_constituents_effective_from'), 'index_constituents', ['effective_from'], unique=False)
    op.create_index(op.f('ix_index_constituents_index_id'), 'index_constituents', ['index_id'], unique=False)
    op.create_table('investigations',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('index_id', sa.Uuid(), nullable=True),
    sa.Column('investigation_type', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('overall_confidence', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_company_id'), 'investigations', ['company_id'], unique=False)
    op.create_index(op.f('ix_investigations_index_id'), 'investigations', ['index_id'], unique=False)
    op.create_index(op.f('ix_investigations_investigation_type'), 'investigations', ['investigation_type'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_index(op.f('ix_investigations_target_date'), 'investigations', ['target_date'], unique=False)
    op.create_index(op.f('ix_investigations_user_id'), 'investigations', ['user_id'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('return_1d', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_7d', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_30d', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'trade_date', name='uq_price_snapshots_company_trade_date')
    )
    op.create_index(op.f('ix_price_snapshots_company_id'), 'price_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_trade_date'), 'price_snapshots', ['trade_date'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('investigation_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_investigation_id'), 'conversations', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('investigation_drivers',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('driver_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=64), nullable=False),
    sa.Column('impact_level', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_drivers_driver_type'), 'investigation_drivers', ['driver_type'], unique=False)
    op.create_index(op.f('ix_investigation_drivers_investigation_id'), 'investigation_drivers', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_drivers_rank'), 'investigation_drivers', ['rank'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('investigation_id', sa.Uuid(), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tool_calls_conversation_id'), 'agent_tool_calls', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_investigation_id'), 'agent_tool_calls', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_status'), 'agent_tool_calls', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_tool_name'), 'agent_tool_calls', ['tool_name'], unique=False)
    op.create_table('evidence_items',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.String(length=255), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['investigation_drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_driver_id'), 'evidence_items', ['driver_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_evidence_type'), 'evidence_items', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_items_investigation_id'), 'evidence_items', ['investigation_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_evidence_items_investigation_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_evidence_type'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_driver_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_agent_tool_calls_tool_name'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_status'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_investigation_id'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_conversation_id'), table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index(op.f('ix_investigation_drivers_rank'), table_name='investigation_drivers')
    op.drop_index(op.f('ix_investigation_drivers_investigation_id'), table_name='investigation_drivers')
    op.drop_index(op.f('ix_investigation_drivers_driver_type'), table_name='investigation_drivers')
    op.drop_table('investigation_drivers')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_investigation_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_price_snapshots_trade_date'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_company_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_investigations_user_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_target_date'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_investigation_type'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_index_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_company_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_index_constituents_index_id'), table_name='index_constituents')
    op.drop_index(op.f('ix_index_constituents_effective_from'), table_name='index_constituents')
    op.drop_index(op.f('ix_index_constituents_company_id'), table_name='index_constituents')
    op.drop_table('index_constituents')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sectors_parent_id'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_code'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_indices_is_active'), table_name='indices')
    op.drop_index(op.f('ix_indices_code'), table_name='indices')
    op.drop_table('indices')
    # ### end Alembic commands ###
