"""add alignment to evidence items

Revision ID: c0266f26723c
Revises: c2d9e4f7a1b3
Create Date: 2026-09-22 23:39:28.666621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0266f26723c'
down_revision: Union[str, Sequence[str], None] = 'c2d9e4f7a1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_items', sa.Column('alignment', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_column('evidence_items', 'alignment')
    # ### end Alembic commands ###
